### ISSUE TITLE
AWS Credentials issue

### ISSUE THREAD

**Issue by skoziara-pgs** [cgonser/swiftmailer-database-s3-spool-bundle#3]
Hi

I've just noticed that this bundle cannot connect to newest AWS SDK.
When I try to upload message to S3, I receive an error:

`  [Aws\Exception\CredentialsException]                                                                                                        
  Error retrieving credentials from the instance profile metadata server. (cURL error 28: Connection timed out after 1001 milliseconds (see   
  http://curl.haxx.se/libcurl/c/libcurl-errors.html))   `

which is related to new AWS configuration, now credentials needs to be in an array such as:
`credentials:
        key: %aws-key%
        secret: %aws-secret%`

Thus if you add this array (while debugging) to $s3Config in DatabaseS3Spool constructor then it will save message to S3. Otherwise it fails with error described above.

Is there any way to fix this?

Btw I'm using:
`"aws/aws-sdk-php-symfony": "^1.2",
"cgonser/swiftmailer-database-s3-spool-bundle": "dev-master"`

**Comment by cgonser** [comment]
Thanks for reporting. Just released a new version in which you can pass credentials configurations to s3 config array. Please refer to README file for details.

**Comment by skoziara-pgs** [comment]
Thanks, it works!
